game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path('rsp/', views.rsp, name="rsp"),
    path('rsp/<str:pick>', views.result, name="result"),
    path('reset/', views.reset, name="reset"),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('page/', include('page.urls')),
]

page/urls.py
from django.urls import path
from . import views

app_name = "page"

urlpatterns = [
    path('', views.index, name="index"),
    path('read/', views.read, name="read"),
    path('create/', views.create, name="create"),
    path('<int:post_id>/', views.detail, name="detail"),
]

game/models.py
from django.db import models

# Create your models here.

page/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
# [코드 작성] Post 모델 작성
class Post(models.Model) : 
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add = True)

game/views.py
from django.shortcuts import render, redirect
from random import *

# Create your views here.
# win(승리), draw(무승부), lose(패배) 횟수를 저장하는 전역변수 생성
win = 0
draw = 0
lose = 0

def rsp(request):
    # [미션] 함수에서 전역변수 설정하기
    global win,draw,lose

    context = {
        "win": win,
        "draw": draw,
        "lose": lose,
    }
    return render(request, "game/rsp.html", context)

def result(request, pick):
    # [미션] 함수에서 전역변수 설정하기
    global win,draw,lose
    
    rsp = ["가위", "바위", "보"]
    # [미션] 'com' 변수에 'rsp' 리스트의 원소들 중 하나를 랜덤하게 저장하기
    com = choice(rsp)

    # 내가 선택한 'pick'과 'com' 변수에 저장된 가위바위보 결과를 비교해서 'result' 변수에 결과(승리, 무승부, 패배)를 저장하는 로직 작성하기
    # win(승리), draw(무승부), lose(패배) 횟수를 가위바위보 결과에 따라 증가시키기
    if pick == com:
        result = "무승부"
        draw += 1
    elif (pick == "가위" and com == "보") or (pick == "바위" and com == "가위") or (pick == "보" and com == "바위"):
        result = "승리"
        win += 1
    else :
        result = "패배"
        lose += 1

    context = {
        "pick": pick,
        # [미션] 'com'키의 value값을 'com'변수값으로 만들기
        "com" : com,
        "result": result,
        "win": win,
        "draw": draw,
        "lose": lose,
    }

    return render(request, "game/result.html", context)

def reset(request):
    # [미션] 함수에서 전역변수 설정하기
    global win,draw,lose   
    
    # [미션] win(승리), draw(무승부), lose(패배) 횟수를 초기화하기
    win,draw,lose = 0,0,0

    # 'urls.py'에서 설정한 app_name인 'game'의 url 경로중 별칭이 'rsp'인 경로로 리다이렉트
    return redirect("game:rsp")

page/views.py
from django.shortcuts import render, redirect
# [코드 작성] models.py의 Post 모델 불러오기
from .models import Post

# Create your views here.
def index(request):
    return render(request, 'page/index.html')

def read(request):
    # [코드 작성] Post 모델의 모든 객체를 리스트로 가져오기
    posts = Post.objects.all()
    context = {
        # [코드 작성] context에 posts 리스트를 딕셔너리 형식으로 넘겨주기
        "posts" : posts,
    }
    return render(request, 'page/read.html', context)

def create(request):
    # 만약 form에서 값을 전송하는 방식이 'POST'일 경우
    if request.method == 'POST':
        # [코드 작성] POST 방식으로 넘어온 값 중 'title'과 'content'의 값을 딕셔너리 형태로 반환
        title = request.POST.get('title')
        content = request.POST.get('content')

        # [코드 작성] Post 모델의 title과 content 필드값에 form으로 넘겨준 값을 저장하는 객체 생성
        Post.objects.create(
              title = title, content = content,
        )
        
        # 앱 이름이 'page'인 urls.py에서 name 속성값이 'read'인 url로 리다이렉트
        return redirect('page:read')
    else:
        return render(request, 'page/create.html')

def detail(request, post_id):
    # [코드 작성] Post 모델의 객체 중 id 값이 post_id와 같은 객체를 가져옴
    
    context = {
        'post': post,
    }
    return render(request, 'page/detail.html', context)

game/templates/game/result.html
{% extends 'game/rsp.html' %}

{% block rsp %}
  <h1>가위바위보 게임 결과</h1>
  
  <!-- [미션] 가위바위보 중에서 내가 선택한 결과 보여주기 -->
  <p>나는 <b></b>를 선택했습니다.</p>

  <!-- [미션] 랜덤하게 선택된 컴퓨터의 결과 보여주기 -->
  <p>컴퓨터는 <b></b>를 선택했습니다.</p>

  <h2 style="color: red;">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

game/templates/game/rsp.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .rsp {
      display: flex;
      flex-wrap: wrap;
      padding: 10px 0;
    }
    .rsp a {
      margin: 0 2px;
      padding: 10px 20px;
      border: 1px solid;
      border-radius: 15px;
      text-decoration: none;
    }
    .rsp a:hover {
      background-color: rgb(225, 225, 255);
    }
    .count {
      width: 25%;
      padding: 10px;
      margin: 10px 0;
      border: 1px solid;
    }
  </style>
{% endblock %}

{% block body %}

  {% block rsp %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'game:reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp">
    <a href="{% url 'game:result' '가위' %}">가위</a>
    <a href="{% url 'game:result' '바위' %}">바위</a>
    <a href="{% url 'game:result' '보' %}">보</a>
  </div>
  
{% endblock %}

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'image/favicon-96x96.png' %}">
  <!-- css를 적용시켜주는 코드 -->
  
</head>
<body>
  <div class="navbar">
    <span>
      <a href="{% url 'page:index' %}">
        <img class="logo" src="{% static 'image/jgcat.jpg' %}" alt="jgcat">
      </a>
    </span>
    <span>
      <a href="{% url 'page:read' %}">글목록</a>
    </span>
    <span>
      <a href="{% url 'page:create' %}">글쓰기</a>
    </span>
    <span>
      <a href="{% url 'game:rsp' %}">가위바위보 게임</a>
    </span>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    /* .navbar : html 코드에서 class 속성값이 "navbar"인 태그에 css 적용 */
    /* navbar 앞의 '.'은 class를 의미 */
    .navbar {
      /* flex : 레이아웃 설정 */
      display: flex;
      /* flex-direction : 레이아웃 배치 방향 설정 */
      flex-direction: row;
      /* flex-wrap : 줄바꿈 방법 */
      flex-wrap: wrap;
      padding: 5px 50px;
      /* background-color : 배경색 설정 */
      background-color: MediumTurquoise;
    }
    
    /* .navbar span : .navbar 태그 안쪽에 있는 span 태그에 css 적용 */
    .navbar span {
      display: flex;
      /* align-items : flex-direction 방향을 기준으로 수직 방향 정렬 */
      align-items: center;
      margin: 0 10px;
    }
    
    .navbar a {
      padding: 3px 6px;
      /* color : 텍스트 색상 설정 */
      color: black;
      /* 1.5rem : html 태그 폰트 크기의 1.5배 */
      font-size: 1.5rem;
      /* text-decoration : 선으로 글자를 꾸미는 속성 */
      text-decoration: none;
    }
    
    /* :hover : 마우스를 올렸을 때의 동작을 설정 */
    .navbar a:hover {
      padding: 3px 6px;
      /* border-radius : 테두리를 둥글게 하는 속성 */
      border-radius: 10px;
      background-color: PaleTurquoise;
    }
    
    .logo {
      display:flex;
      width: 60px;
      margin: 5px;
    }
  </style>
  {% block head %}
  {% endblock %}

  

page/templates/page/create.html
{% extends 'base.html' %}

{% block head %}
  <style>
    table {
      width: 100%;
      margin: auto;
    }
    /* tr td:nth-of-type(2) : tr 태그의 바로 하위 태그인 td 태그 중 2번째에 css 적용 */
    tr td:nth-of-type(2) {
      width: 90%;
    }
    input{
      padding: 5px 10px;
      font-family: 'GangwonEdu_OTFBoldA';
      font-size: 16px;
    }
    /* input[type=text] : input 태그 중 type 속성명의 속성값이 text인 태그에 css 적용 */
    input[type=text] {
      width: 100%;
      height: 20px;
      border: 1px solid;
      border-radius: 5px;
    }
    textarea {
      width: 100%;
      padding: 5px 10px;
      border: 1px solid;
      border-radius: 5px;
      /* font-family : 폰트 종류 */
      font-family: 'GangwonEdu_OTFBoldA';
      font-size: 16px;
    }
    .right {
      padding-top: 20px;
      /* text-align : 텍스트의 정렬 방향 */
      text-align: right;
    }
    .button {
      padding: 5px 10px;
      border: 1px solid;
      border-radius: 10px;
      background-color: Khaki;
      color: SaddleBrown;
      text-decoration: none;
      /* cursor : 커서 모양 변경 */
      cursor: pointer;
    }
  </style>
{% endblock %}

{% block body %}
  <h1>글쓰기</h1>

  <!-- [코드 추가] form의 전달방식을 post로 설정하기 -->
  <form action="" method = "post">
    <!-- [코드 작성] csrf_token 설정하기 -->
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <!-- [코드 수정] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'title'로 설정하기 -->
        <td><input class="title" name="title" id="title" type="text"></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <!-- [코드 수정] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'content'로 설정하기 -->
          <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </td>
      </tr>
    </table>
    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}

page/templates/page/detail.html
{% extends 'base.html' %}

{% block head %}
  <style>
    table {
      width: 100%;
    }
    td {
      padding: 10px;
      border-bottom: 2px solid;
    }
    .title {
      font-size: 1.5rem;
    }
    .content {
      display: flex;
      justify-content: left;
      /* min-height : 최소 높이 지정 */
      /* 20vh : 현재 스크린의 높이를 기준으로 20%의 높이를 차지 */
      min-height: 20vh;
      margin: 10px 0;
    }
    .right {
      padding-top: 20px;
      text-align: right;
    }
    .button {
      padding: 8px 10px;
      border: 1px solid;
      border-radius: 10px;
      background-color: Khaki;
      color: SaddleBrown;
      text-decoration: none;
    }
  </style>
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <table>
    <tr>
      <td class="title">{{post.title}}</td>
    </tr>
    <tr>
      <!-- [코드 추가] 날짜를 보여주는 형식을 'Y-m-d A f'로 지정하기 -->
      <td>작성일 : {{post.date}}</td>
    </tr>
    <tr>
      <td class="content">{{post.content}}</td>
    </tr>
  </table>

  
  <div class="right">
    <a class="button" href="{% url 'page:read' %}">글 목록</a>
  </div>
{% endblock %}

page/templates/page/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <style>
    img {
      /* 30% : 상위 태그(없으면 body 태그)의 넓이를 기준으로 30%의 넓이를 가짐 */
      width: 30%;
      border-radius: 10px;
    }
  </style>
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>
  
  <p>오늘의 목표</p>
  <ol>
    <li>가위바위보 게임을 완성해봅시다.</li>
    <li>Django의 Model을 사용해봅니다.</li>
    <li>DB에 데이터를 저장하고, 저장한 데이터를 읽어올 수 있도록 코딩해봅시다.</li>
  </ol>

  <img src="{% static 'image/walnut.jpg' %}" alt="walnut">
{% endblock %}

page/templates/page/read.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .right {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      /* align-items : flex-direction 방향을 기준으로 정렬 */
      justify-content: right;
      text-align: right;
      padding-bottom: 20px;
    }
    .button {
      padding: 5px 10px;
      border: 1px solid;
      border-radius: 10px;
      background-color: Khaki;
      color: SaddleBrown;
      text-decoration: none;
    }
    table {
      width: 100%;
      margin: auto;
    }
    .index {
      width: 1.2rem;
      text-align: center;
    }
    .title {
      width: auto;
      padding: 5px 20px;
    }
    .date {
      width: 6rem;
      text-align: center;
    }
    th {
      padding: 5px;
      border-bottom: 2px solid;
    }
    td {
      padding: 5px 10px;
      border-bottom: 1px solid;
    }
    td a {
      color: black;
      text-decoration: none;
    }
    td a:hover {
      color: purple;
      text-decoration: underline;
    }
  </style>
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="right">
    <a class="button" href="{% url 'page:create' %}">글쓰기</a>
  </div>

  <table>
    <tr>
      <th class="index">번호</th>
      <th class="title">제목</th>
      <th class="date">날짜</th>
    </tr>
    <!-- [코드 추가] reversed를 이용해 for문을 거꾸로 반복하기 -->
    {% for post in posts reversed %}
      <tr>
        <!-- [코드 수정] 반복문의 index를 거꾸로 가져오는 revcounter 사용 -->
        <td class="index">{{forloop.revcounter}}</td>
        <td class="title"><a href="{% url 'page:detail' post.id %}">{{post.title}}</a></td>
        <!-- [코드 추가] 날짜를 보여주는 형식을 'Y-m-d'로 지정하기 -->
        <td class="date">{{post.date|date:'Y/m/d'}}</td>
      </tr>
    <!-- for문의 리스트가 비어있을 경우에 보여주는 내용 -->
    {% empty %}
      <tr>
        <td class="index">-</td>
        <td class="title">글을 작성해주세요.</td>
        <td class="date">-</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}